import java.util.regex.Matcher
import java.util.regex.Pattern
import net.neoforged.neodev.CheckSplitSources

plugins {
	id 'java'
    id 'net.neoforged.gradleutils' version '5.1.1'
    id 'dev.lukebemish.immaculate' version '0.1.16' apply false
    id 'net.neoforged.licenser' version '0.7.5'
    id 'neoforge.formatting-conventions'
    id 'neoforge.versioning'
}

// If an external version is defined, always use that
ext.isPreReleaseVersion = false

final fixedProjectVersion = project.providers.gradleProperty("version").getOrElse(null)
if (fixedProjectVersion == null) {
    if (project.minecraft_version.contains('-')) {
        ext.isPreReleaseVersion = true
        // Match the manual snapshot release suffix (e.g. -alpha.M+snapshot-N) with M=0 and a suffixed .<timestamp>
        // Separate out the -snapshot-N or -rc-N suffix
        final preReleaseSuffix = project.minecraft_version.split("-", 2)[1]
        project.version = "${project.neoforge_snapshot_next_stable}.0-alpha.0+${preReleaseSuffix}.${(new Date()).format('yyyyMMdd.HHmmss', TimeZone.getTimeZone('UTC'))}"
    } else {
        project.version = gradleutils.version.toString()
    }
} else {
    project.version = fixedProjectVersion
}

// Print version, generally useful to know - also appears on CI
System.out.println("NeoForge version ${project.version}")

allprojects {
    version = rootProject.version
    group = 'net.neoforged'

    apply plugin: 'java'

    java.toolchain.languageVersion.set(JavaLanguageVersion.of(project.java_version))
}

// Remove src/ sources from the root project. They are used in the neoforge subproject.
sourceSets {
    main {
        java {
            srcDirs = []
        }
        resources {
            srcDirs = []
        }
    }
}