import io.codechicken.diffpatch.cli.PatchOperation

plugins {
	id 'java'
    id 'net.neoforged.gradleutils' version '5.1.1'
    id 'dev.lukebemish.immaculate' version '0.1.16' apply false
    id 'net.neoforged.licenser' version '0.7.5'
    id 'neoforge.formatting-conventions'
    id 'neoforge.versioning'
}

// If an external version is defined, always use that
ext.isPreReleaseVersion = false

final fixedProjectVersion = project.providers.gradleProperty("version").getOrElse(null)
if (fixedProjectVersion == null) {
    if (project.minecraft_version.contains('-')) {
        ext.isPreReleaseVersion = true
        // Match the manual snapshot release suffix (e.g. -alpha.M+snapshot-N) with M=0 and a suffixed .<timestamp>
        // Separate out the -snapshot-N or -rc-N suffix
        final preReleaseSuffix = project.minecraft_version.split("-", 2)[1]
        project.version = "${project.neoforge_snapshot_next_stable}.0-alpha.0+${preReleaseSuffix}.${(new Date()).format('yyyyMMdd.HHmmss', TimeZone.getTimeZone('UTC'))}"
    } else {
        project.version = gradleutils.version.toString()
    }
} else {
    project.version = fixedProjectVersion
}

// Print version, generally useful to know - also appears on CI
System.out.println("NeoForge version ${project.version}")

allprojects {
    version = rootProject.version
    group = 'net.neoforged'

    apply plugin: 'java'

    java.toolchain.languageVersion.set(JavaLanguageVersion.of(project.java_version))
}

// Remove src/ sources from the root project. They are used in the neoforge subproject.
sourceSets {
    main {
        java {
            srcDirs = []
        }
        resources {
            srcDirs = []
        }
    }
}

tasks.register('copyCB', Copy) {
    group = 'neotenet'

    from('projects/bukkit/src/main/java') {
        exclude 'com/**'
    }
    from('projects/craftbukkit/src/main/java') {
        exclude 'com/**'
    }

    into 'projects/neotenet/src/main/java'

    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

def rootDir = rootProject.projectDir

tasks.register('prepareCleanCB', Copy) {
    group = 'neotenet'

    from('projects/bukkit/src/main/java') {
        exclude 'com/mojang/**'
    }
    from('projects/craftbukkit/src/main/java') {
        exclude 'com/mojang/**'
    }
    into 'projects/cb-base/src/main/java'
    duplicatesStrategy = DuplicatesStrategy.INCLUDE
}

import io.codechicken.diffpatch.cli.DiffOperation
import io.codechicken.diffpatch.util.Input.MultiInput
import io.codechicken.diffpatch.util.Output.MultiOutput

tasks.register('genCBPatchesJar') {
    group = 'neotenet'
    dependsOn 'prepareCleanCB'

    inputs.dir('projects/cb-base/src/main/java/org/bukkit')
    inputs.dir('projects/neotenet/src/main/java/org/bukkit')
    outputs.file('projects/neotenet/cb-patches.jar')

    doLast {
        def baseDir = new File(rootDir, 'projects/cb-base/src/main/java/org/bukkit').toPath()
        def modifiedDir = new File(rootDir, 'projects/neotenet/src/main/java/org/bukkit').toPath()
        def patchesJar = new File(rootDir, 'projects/neotenet/cb-patches.jar').toPath()

        java.nio.file.Files.deleteIfExists(patchesJar)

        def builder = DiffOperation.builder()
                .logTo(logger::lifecycle)
                .baseInput(MultiInput.folder(baseDir))
                .changedInput(MultiInput.folder(modifiedDir))
                .patchesOutput(MultiOutput.detectedArchive(patchesJar))
                .autoHeader(true)
                .level(io.codechicken.diffpatch.util.LogLevel.WARN)
                .summary(false)
                .aPrefix('a/')
                .bPrefix('b/')
                .lineEnding('\n')

        def result = builder.build().operate()
        int exit = result.exit
        if (exit != 0 && exit != 1) {
            throw new RuntimeException("Diffpatch Failed，Code: " + exit)
        }
        logger.lifecycle('Patched Successful: cb-patches.jar')
    }
}

tasks.register('applyCBPatches') {
    group = 'neotenet'
    dependsOn 'copyCB'

    inputs.file('projects/neotenet/cb-patches.jar')
    outputs.dir('projects/neotenet/src/main/java/org/bukkit')

    doLast {
        def patchesJar = new File(rootDir, 'projects/neotenet/cb-patches.jar')
        if (!patchesJar.exists()) {
            logger.lifecycle('cb-patches.jar None Exist，Skip')
            return
        }
        def baseDir = new File(rootDir, 'projects/cb-base/src/main/java/org/bukkit').toPath()
        def targetDir = new File(rootDir, 'projects/neotenet/src/main/java/org/bukkit').toPath()

        def builder = PatchOperation.builder()
                .logTo(logger::lifecycle)
                .baseInput(MultiInput.folder(baseDir))
                .patchesInput(MultiInput.detectedArchive(patchesJar.toPath()))
                .patchedOutput(MultiOutput.folder(targetDir))
                .level(io.codechicken.diffpatch.util.LogLevel.WARN)
                .summary(false)
                .lineEnding('\n')

        def result = builder.build().operate()
        if (result.exit != 0 && result.exit != 1) {
            throw new RuntimeException("Failed，Code: " + result.exit)
        }
        logger.lifecycle('Applied Successful')
    }
}