plugins {
    id 'java'
}

group = 'org.taiyitistmc'
version = rootProject.version

base {
    archivesName = "neotaiyitist"
}

def neotaiyitistProjectDir = rootProject.layout.projectDirectory.dir("projects/neotaiyitist")
def installerJarDir = neotaiyitistProjectDir.dir("build/libs")
def installerJarFile = installerJarDir.file("neotaiyitist-${version}-installer.jar")


tasks.register('launcherJar', Jar) {
    archiveClassifier = 'launcher'

    manifest {
        attributes(
                "Implementation-Title": project.name,
                "Implementation-Version": version,
                "Main-Class": "org.taiyitistmc.launcher.NeoTaiyitistLauncher",
        )
    }

    from sourceSets.main.output

    dependsOn project(':neotaiyitist').tasks.named('installerJar')

    from(installerJarFile.asFile) {
        into('META-INF/installer')
    }
}