plugins {
    id 'java'
}

group = 'org.taiyitistmc'
version = rootProject.version

base {
    archivesName = "neotaiyitist"
}

dependencies {
    compileOnly "cpw.mods:bootstraplauncher:${project.bootstraplauncher_version}"
}

// 使用 layout API 定义文件路径
def neotaiyitistProjectDir = rootProject.layout.projectDirectory.dir("projects/neotaiyitist")
def installerJarDir = neotaiyitistProjectDir.dir("build/libs")
def installerJarFile = installerJarDir.file("neotaiyitist-${version}-installer.jar")

// 创建一个新的任务 launcherJar
tasks.register('launcherJar', Jar) {
    // 设置 jar 文件的分类器，避免与默认 jar 文件名冲突
    archiveClassifier = 'launcher'

    // 复制默认 jar 的配置
    manifest {
        attributes(
                "Implementation-Title": project.name,
                "Implementation-Version": version,
                "Main-Class": "org.taiyitistmc.launcher.NeoTaiyitistLauncher",
        )
    }

    // 包含当前项目编译后的类文件
    from sourceSets.main.output

    // 在执行此任务前先执行 neotaiyitist 项目的 installerJar 任务
    dependsOn project(':neotaiyitist').tasks.named('installerJar')

    // 将 installer jar 添加到 resources 中，使其被打包进最终的 jar
    from(installerJarFile.asFile) {
        // 可以指定在 jar 中的路径
        into('META-INF/installer')
    }
}