plugins {
    id 'java'
    id 'net.neoforged.gradleutils' version '4.0.1'
}

group = 'org.celestial_artistry.neotenet'
version = '1.21.1-' + gradleutils.gitInfo.abbreviatedId // NeoTenet

base {
    archivesName = "neotenet-launcher"
}

def neotaiyitistProjectDir = rootProject.layout.projectDirectory.dir("projects/neotenet")
def installerJarDir = neotaiyitistProjectDir.dir("build/libs")
def installerJarFile = installerJarDir.file("neotenet-${rootProject.version}-installer.jar")


tasks.register('launcherJar', Jar) {
    manifest {
        attributes(
                "Implementation-Title": project.name,
                "Implementation-Version": version,
                "Main-Class": "org.celestial_artistry.neotenet.launcher.NeoTenetLauncher",
        )
    }

    from sourceSets.main.output

    dependsOn project(':neotenet').tasks.named('installerJar')

    from(installerJarFile.asFile) {
        into('META-INF/installer')
    }
}