import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

plugins {
    id 'java'
    id 'net.neoforged.gradleutils' version '4.0.1'
    id 'com.gradleup.shadow' version '9.3.0'
}

group = 'org.celestial_artistry.neotenet'
version = '1.21.1-' + gradleutils.gitInfo.abbreviatedId // NeoTenet

base {
    archivesName = "neotenet-launcher"
}

def neotenetDir = rootProject.layout.projectDirectory.dir("projects/neotenet")
def buildJarDir = neotenetDir.dir("build/libs")
def neoDevDir = neotenetDir.dir("build/neodev")
def universalJarFile = buildJarDir.file("neotenet-${rootProject.version}-universal.jar")
def installProfile = neoDevDir.file("installer-profile.json")
def serverArgs = neoDevDir.file("unix-server-args.txt")
def serverPatch = neoDevDir.file("server-binpatches.lzma")


dependencies {
    implementation("com.fasterxml.jackson.core:jackson-databind:2.20.1")

    compileOnly "cpw.mods:bootstraplauncher:${project.bootstraplauncher_version}"
    compileOnly "net.neoforged.installertools:installertools:2.1.2"
    compileOnly "net.neoforged.installertools:jarsplitter:2.1.2"
    compileOnly "net.neoforged:AutoRenamingTool:2.0.3"
    compileOnly "net.neoforged.installertools:binarypatcher:2.1.2"
}

tasks.register('launcherJar', ShadowJar) {
    manifest {
        attributes(
                "Implementation-Title": project.name,
                "Implementation-Version": version,
                "Main-Class": "org.teneted.neotenet.launcher.NeoTenetLauncher",
                "Launcher-Agent-Class": "org.teneted.neotenet.launcher.NeoTenetAgent",
        )
    }

    configurations = project.configurations.named('runtimeClasspath').map { [it] }

    from sourceSets.main.output

    dependsOn project(':neotenet').tasks.named('installerJar')


    from(universalJarFile.asFile) { into('neodev/') }
    from(installProfile.asFile) { into('neodev/') }
    from(serverArgs.asFile) { into('neodev/') }
    from(serverPatch.asFile) { into('neodev/') }
}